# Generated by Django 4.2.1 on 2023-06-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ollegro_payments', '0002_payment_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Count of products units'),
        ),
    ]
