# Generated by Django 4.2.1 on 2023-06-11 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_total_reserved'),
        ('ollegro_payments', '0003_payment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='product',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchases', to='products.product', verbose_name='Product'),
            preserve_default=False,
        ),
    ]
