# Generated by Django 4.2.1 on 2023-06-10 18:08

from django.db import migrations, models
import django.db.models.deletion
import random


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(default=random.randint(1, 1000), editable=False, max_length=16, unique=True, verbose_name='Category code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='products.category', verbose_name='Product category'),
        ),
    ]
