# Generated by Django 4.2.1 on 2023-06-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_code_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=16, unique=True, verbose_name='Category code'),
        ),
    ]
