# Generated by Django 4.2.1 on 2023-06-10 20:28

from django.db import migrations, models
import random


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options_alter_productproperty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=random.randint(1, 1000), max_digits=9, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(verbose_name='Product code'),
        ),
    ]
