# Generated by Django 4.2.1 on 2023-06-10 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_price_alter_product_sku'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productproperty',
            unique_together={('code', 'value', 'category')},
        ),
    ]
