# Generated by Django 4.2.1 on 2023-06-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productproperty_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_reserved',
            field=models.IntegerField(default=0, verbose_name='Reserved products'),
        ),
    ]
