# Generated by Django 4.2.1 on 2023-06-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_lot_rate_lot_final_rate_lot_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
