# Generated by Django 4.2.1 on 2023-06-15 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_lot_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='final_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='final_lot', to='products.rate'),
        ),
    ]
