# Generated by Django 4.2.1 on 2023-06-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_lot_final_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=9),
        ),
    ]
