# Generated by Django 4.2.1 on 2023-06-15 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_lot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rates', to='products.lot'),
        ),
    ]
